title: colinbarrett dot net
author: Colin Barrett
email: barrettcolin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Colin Barrett. I am a computer programmer. This is my personal website.

twitter_username: barrettcolin
github_username:  barrettcolin

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - jemoji

